### ISSUE TITLE
Inventory.find problem

### ISSUE THREAD

**Issue by pango47** [lordmauve/adventurelib#34]
Seems to be a problem with inventory.find though it might be my error!

I get the following:

You are in a room it is roomy
A bar of silver is here.
> take silver
You pick up the bar of silver.

> cast spell
Magic issues forth from your fingers...
You drop the bar of silver.

> inventory
You have:
* sledgehammer

> cast spell
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    start()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/adventurelib.py", line 536, in start
    _handle_command(cmd)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/adventurelib.py", line 509, in _handle_command
    func(**args)
  File "main.py", line 78, in spell
    if inventory.find('silver'):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/adventurelib.py", line 236, in find
    if name.lower() in item.aliases:
AttributeError: 'str' object has no attribute 'aliases'

from the attached code:

[samplead.txt](https://github.com/lordmauve/adventurelib/files/5361043/samplead.txt)

**Comment by yonderbread** [comment]
[Bag.find](https://github.com/lordmauve/adventurelib/blob/3b6ff69ef24d75c2fd0b1f5f1fd105d0f2dffa7d/adventurelib.py#L229) takes a string as it's argument, not a object. You're getting this error because `.lower()` is a method for strings only.
